#!/usr/bin/env sh
set -eu

script_dir=$(CDPATH= cd "$(dirname "$0")" && pwd)
repo_root=$(CDPATH= cd "$script_dir/.." && pwd)
root=${1:-"$repo_root/android_root"}

mkdir -p "$root"

for dir in \
  acct apex cache config debug_ramdisk dev linkerconfig metadata mnt oem proc sdcard sys tmp \
  data/app data/data data/local/tmp data/misc data/system \
  storage/emulated/0 \
  system/app system/bin system/etc/init system/etc/permissions system/etc/sysconfig system/framework system/lib system/lib64 system/priv-app \
  vendor/app vendor/bin vendor/etc/init vendor/framework vendor/lib vendor/lib64 vendor/priv-app \
  product/app product/etc/init product/framework product/lib product/lib64 product/priv-app \
  odm/app odm/etc/init odm/framework odm/lib odm/lib64 odm/priv-app
do
  mkdir -p "$root/$dir"
done

write_if_missing() {
  path=$1
  if [ -e "$path" ]; then
    cat >/dev/null
    return 0
  fi

  mkdir -p "$(dirname "$path")"
  cat >"$path"
}

write_if_missing "$root/init.rc" <<'EOF'
# Minimal Android init stub for the Vodka runtime.
#
# This file documents the first filesystem contract. It is not expected to boot
# a complete Android userspace until the runtime service model is implemented.

import /system/etc/init/*.rc
import /vendor/etc/init/*.rc
import /product/etc/init/*.rc
import /odm/etc/init/*.rc

on early-init
    mkdir /dev 0755 root root
    mkdir /proc 0555 root root
    mkdir /sys 0555 root root
    mkdir /mnt 0755 root root

on init
    export ANDROID_ROOT /system
    export ANDROID_DATA /data
    export ANDROID_STORAGE /storage
    export EXTERNAL_STORAGE /sdcard

    mkdir /cache 0770 system cache
    mkdir /data 0771 system system
    mkdir /data/app 0771 system system
    mkdir /data/data 0771 system system
    mkdir /data/local 0751 shell shell
    mkdir /data/local/tmp 0771 shell shell
    mkdir /data/misc 01771 system misc
    mkdir /data/system 0775 system system
    mkdir /storage 0755 root root
    mkdir /storage/emulated 0555 root root
    mkdir /tmp 0771 shell shell
EOF

write_if_missing "$root/README.md" <<'EOF'
# Vodka Android Root

This directory is the initial Android filesystem view presented to Android
userspace. It is a skeleton, not a bootable Android image.

## Contract

- `ANDROID_ROOT` maps to `/system`.
- `ANDROID_DATA` maps to `/data`.
- Runtime-writable state starts under `/data`, `/cache`, and `/tmp`.
- Host pseudo filesystems such as `/proc`, `/sys`, and `/dev` are mount points,
  not source-controlled content.
- Partition-style directories (`/system`, `/vendor`, `/product`, `/odm`) are
  separate so later import steps can mirror modern Android layouts.

## Current Scope

The root currently provides:

- Android-like directory hierarchy.
- Minimal `init.rc`, `ueventd.rc`, and `fstab.vodka` stubs.
- Generic property files for early runtime discovery.
- Empty application, framework, library, and init-extension directories.

The root does not yet provide ART, Zygote, PackageManager, Binder services,
graphics/audio/input bridges, or native library translation.
EOF

write_if_missing "$root/fstab.vodka" <<'EOF'
# Android fs_mgr-style mount table for Vodka's initial root.
#
# <src>     <mount_point>  <type>  <mount_flags>           <fs_mgr_flags>
proc        /proc          proc    nosuid,nodev,noexec     wait
sysfs       /sys           sysfs   nosuid,nodev,noexec     wait
tmpfs       /dev           tmpfs   mode=0755,nosuid        wait
tmpfs       /mnt           tmpfs   mode=0755,nosuid,nodev  wait
tmpfs       /tmp           tmpfs   mode=1777,nosuid,nodev  wait
EOF

write_if_missing "$root/ueventd.rc" <<'EOF'
# Device node permissions expected by early Android userspace.
#
# Host integration will decide which nodes are passed through, emulated, or
# backed by Vodka services.

/dev/null       0666 root root
/dev/zero       0666 root root
/dev/full       0666 root root
/dev/random     0666 root root
/dev/urandom    0666 root root
/dev/ashmem     0666 root root
/dev/binder     0666 root root
/dev/hwbinder   0666 root root
/dev/vndbinder  0666 root root
EOF

write_if_missing "$root/default.prop" <<'EOF'
# Root-level properties for the initial Vodka Android environment.
#
# These values are deliberately generic. Device-specific values should be
# generated by the runtime or imported from a chosen Android base.

ro.secure=0
ro.debuggable=1
ro.adb.secure=0
ro.vodka.root=1
ro.vodka.root.version=0
EOF

write_if_missing "$root/system/build.prop" <<'EOF'
# Generic system properties for Vodka's initial Android root.

ro.product.brand=Vodka
ro.product.manufacturer=Vodka
ro.product.model=Vodka Linux Runtime
ro.product.name=vodka_x86_64
ro.product.device=vodka
ro.build.product=vodka

ro.build.type=userdebug
ro.build.tags=test-keys
ro.build.version.sdk=35
ro.build.version.release=15
ro.build.version.codename=REL
ro.build.version.incremental=0

ro.product.cpu.abilist=x86_64,x86
ro.product.cpu.abilist64=x86_64
ro.product.cpu.abilist32=x86
ro.dalvik.vm.isa.x86_64=x86_64
ro.dalvik.vm.isa.x86=x86

persist.sys.locale=en-US
ro.config.low_ram=false
EOF

write_if_missing "$root/vendor/build.prop" <<'EOF'
# Vendor partition properties for the initial Vodka root.

ro.vendor.vodka.root=1
EOF

write_if_missing "$root/product/build.prop" <<'EOF'
# Product partition properties for the initial Vodka root.

ro.product.product.brand=Vodka
ro.product.product.name=vodka
ro.product.product.device=vodka
ro.product.product.model=Vodka Linux Runtime
EOF

write_if_missing "$root/system/etc/hosts" <<'EOF'
127.0.0.1 localhost
::1 localhost ip6-localhost
EOF

printf 'Android root skeleton is ready: %s\n' "$root"
